In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import matplotlib.pylab as plt

In [2]:
olddf=pd.read_json('../01_Preprocessing//First.json').sort_index()

In [3]:
olddf.head(2)

country  countryCoded     degree  degreeCoded       eng  engCoded  \
2  united kingdom             4  Doctorate            1      High         1   
3   united states             0  Doctorate            1  VeryHigh         0   

   fieldGroup  fund  gpaBachelors  gpaMasters    gre highLevelBachUni  \
2           7  True           3.5    3.442986  False            False   
3           5  True           2.5    3.500000   True             True   

  highLevelMasterUni  paper     targetUni  uniAccepted uniBachelors  \
2              False    8.0   heriot-watt          n/a         azad   
3              False   13.0  northwestern  switzerland      mashhad   

       uniMasters   uniSelected  year  
2             n/a   heriot-watt  2007  
3  portland state  northwestern  2010

In [4]:
olddf.targetUni.replace('n/a',np.nan,inplace=True)

In [5]:
olddf.columns

Index([u'country', u'countryCoded', u'degree', u'degreeCoded', u'eng',
       u'engCoded', u'fieldGroup', u'fund', u'gpaBachelors', u'gpaMasters',
       u'gre', u'highLevelBachUni', u'highLevelMasterUni', u'paper',
       u'targetUni', u'uniAccepted', u'uniBachelors', u'uniMasters',
       u'uniSelected', u'year'],
      dtype='object')

In [6]:
df=olddf[['countryCoded', 'degreeCoded','engCoded', 'fieldGroup', 
          'gpaBachelors','gre', 'highLevelBachUni', 
          'paper']]

In [7]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(df, olddf.fund)
y_pred = gnb.predict(df)
print("Number of mislabeled points out of a total %d points : %d"
      % (df.shape[0],(olddf.fund != y_pred).sum()))

Number of mislabeled points out of a total 3526 points : 843


In [8]:
me=[1, 0,2, 0, 2.5,False, False,1]
gnb.predict([me])

array([False], dtype=bool)

In [9]:
gnb.predict_proba([me])

array([[ 0.96836683,  0.03163317]])

In [10]:
gnb.classes_

array([False,  True], dtype=bool)