In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [2]:
df=pd.read_json('../01_Preprocessing/First.json').sort_index()

In [3]:
df.head(2)

country  countryCoded     degree  degreeCoded       eng  engCoded  \
2  united kingdom             4  Doctorate            1      High         1   
3   united states             0  Doctorate            1  VeryHigh         0   

   fieldGroup  fund  gpaBachelors  gpaMasters    gre highLevelBachUni  \
2           7  True           3.5    3.442986  False            False   
3           5  True           2.5    3.500000   True             True   

  highLevelMasterUni  paper     targetUni  uniAccepted uniBachelors  \
2              False    6.0   heriot-watt          n/a         azad   
3              False   10.5  northwestern  switzerland      mashhad   

       uniMasters   uniSelected  year  
2             n/a   heriot-watt  2007  
3  portland state  northwestern  2010

# RandomForest (For MS)

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
df=df[df.degreeCoded==0]
df=df[['countryCoded','engCoded', 'fieldGroup','fund','gpaBachelors','gre', 'highLevelBachUni', 'paper']]

In [6]:
df.head()

countryCoded  engCoded  fieldGroup   fund  gpaBachelors    gre  \
6              2         1           0  False      3.000000   True   
7              3         0          10   True      2.611309  False   
8              1         2          10  False      3.000000  False   
9              0         0           0   True      3.500000  False   
12             0         1           0   True      3.500000   True   

   highLevelBachUni  paper  
6              True    0.0  
7             False    0.0  
8              True    0.0  
9              True    1.0  
12            False    0.5

In [7]:
clf= RandomForestClassifier(n_estimators=10,random_state=99)
clf=clf.fit(df.iloc[:, (df.columns != 'fund')],df.fund)

In [8]:
df.iloc[:, (df.columns != 'fund')].columns

Index([u'countryCoded', u'engCoded', u'fieldGroup', u'gpaBachelors', u'gre',
       u'highLevelBachUni', u'paper'],
      dtype='object')

In [9]:
# Check it fit on itself
clf.predict(df.ix[range(6,10)][['countryCoded', 'engCoded', 'fieldGroup', 'gpaBachelors', 'gre','highLevelBachUni','paper']])

array([False,  True, False,  True], dtype=bool)

## check my situation

In [10]:
me=[1, 2, 0, 2.5, False,False,0]
clf.predict([me])

array([False], dtype=bool)

In [11]:
clf.predict_proba([me])

array([[ 1.,  0.]])

In [12]:
clf.classes_

array([False,  True], dtype=bool)

In [13]:
me=[1, 2, 0, 2.5, False,False,1]
clf.predict([me])

array([ True], dtype=bool)

In [14]:
clf.predict_proba([me])

array([[ 0.4,  0.6]])

In [15]:
me=[1, 2, 0, 2.5, False,False,0.5]
clf.predict([me])

array([False], dtype=bool)

In [16]:
clf.predict_proba([me])

array([[ 0.8,  0.2]])